//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4016
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoreUI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CoreUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static byte[] CheckDsbldBlank {
            get {
                object obj = ResourceManager.GetObject("CheckDsbldBlank", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] CheckDsbldCheck {
            get {
                object obj = ResourceManager.GetObject("CheckDsbldCheck", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] CheckDsbldInd {
            get {
                object obj = ResourceManager.GetObject("CheckDsbldInd", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] CheckHoverBlank {
            get {
                object obj = ResourceManager.GetObject("CheckHoverBlank", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] CheckHoverCheck {
            get {
                object obj = ResourceManager.GetObject("CheckHoverCheck", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] CheckHoverInd {
            get {
                object obj = ResourceManager.GetObject("CheckHoverInd", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] CheckNormBlank {
            get {
                object obj = ResourceManager.GetObject("CheckNormBlank", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] CheckNormCheck {
            get {
                object obj = ResourceManager.GetObject("CheckNormCheck", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] CheckNormInd {
            get {
                object obj = ResourceManager.GetObject("CheckNormInd", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] CheckPressBlank {
            get {
                object obj = ResourceManager.GetObject("CheckPressBlank", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] CheckPressCheck {
            get {
                object obj = ResourceManager.GetObject("CheckPressCheck", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] CheckPressInd {
            get {
                object obj = ResourceManager.GetObject("CheckPressInd", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] RadioDsbldBlank {
            get {
                object obj = ResourceManager.GetObject("RadioDsbldBlank", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] RadioDsbldInd {
            get {
                object obj = ResourceManager.GetObject("RadioDsbldInd", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] RadioDsbldRadio {
            get {
                object obj = ResourceManager.GetObject("RadioDsbldRadio", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] RadioHoverBlank {
            get {
                object obj = ResourceManager.GetObject("RadioHoverBlank", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] RadioHoverInd {
            get {
                object obj = ResourceManager.GetObject("RadioHoverInd", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] RadioHoverRadio {
            get {
                object obj = ResourceManager.GetObject("RadioHoverRadio", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] RadioNormBlank {
            get {
                object obj = ResourceManager.GetObject("RadioNormBlank", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] RadioNormInd {
            get {
                object obj = ResourceManager.GetObject("RadioNormInd", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] RadioNormRadio {
            get {
                object obj = ResourceManager.GetObject("RadioNormRadio", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] RadioPressBlank {
            get {
                object obj = ResourceManager.GetObject("RadioPressBlank", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] RadioPressInd {
            get {
                object obj = ResourceManager.GetObject("RadioPressInd", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] RadioPressRadio {
            get {
                object obj = ResourceManager.GetObject("RadioPressRadio", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
