//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TowerSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Leaderboard
    {
        public long Rank { get; set; }
        public string UserName { get; set; }
        public int ELO { get; set; }
        public int LinearELO { get; set; }
    }
}
